version: '2'

services:
        #- ./web/nginx.conf:/etc/nginx/nginx.conf

  app:
    restart: always
    image: halohub/halo
    #container_name: halo
    ports:
      - 8090:8090
    extra_hosts:
      - "smtp.gmail.com:172.16.44.1"
    environment:
      - VIRTUAL_PORT=8090
        #- VIRTUAL_HOST=localhost  # 你的博客地址（务必修改）
      #- LETSENCRYPT_HOST=localhost # 你的博客地址 （务必修改）
      #- LETSENCRYPT_EMAIL=i@example.com # 证书所有者的邮箱，快过期时会提醒（务必修改）
      - MAX_UPLOAD_SIZE=1024m
      - JVM_OPTS=-Xms256m -Xmx256m
      - JVM_XMS=256m
      - JVM_XMX=256m
    volumes:
      - ./app/www:/root/.halo
  db:
    image: mysql:5.7.35
    #command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=halo123
